//! Built-in detection contracts.
//!
//! Built-ins combine candidate discovery, severity and validator selection into
//! reusable [`RuleSpec`] values.

mod contextual;
mod deterministic;

pub use contextual::{
    AUTHORIZATION_BASIC, AUTHORIZATION_BEARER, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY,
    AWS_SESSION_TOKEN, AWS_TEMPORARY_ACCESS_KEY_ID, AZURE_CLIENT_SECRET,
    AZURE_SHARED_ACCESS_SIGNATURE, AZURE_STORAGE_ACCOUNT_KEY, CARGO_REGISTRY_ENV_TOKEN,
    CARGO_REGISTRY_TOKEN, DATABASE_CONNECTION_PASSWORD, DATABASE_PASSWORD_FIELD,
    DOCKER_REGISTRY_AUTH, GCP_ESCAPED_PRIVATE_KEY, GCP_PRIVATE_KEY, GCP_PRIVATE_KEY_ID,
    GENERIC_API_KEY, GENERIC_AUTH_TOKEN, GENERIC_SECRET, HTPASSWD_PASSWORD_VERIFIER,
    NETRC_PASSWORD, NPM_REGISTRY_AUTH, NPM_REGISTRY_AUTH_TOKEN, NPM_REGISTRY_PASSWORD,
    PASSPHRASE_FIELD, PASSWORD_FIELD, SENSITIVE_HASH, SHADOW_PASSWORD_VERIFIER,
    WIREGUARD_PRESHARED_KEY, WIREGUARD_PRIVATE_KEY,
};
pub use deterministic::{
    CLOUDFLARE_ACCOUNT_API_TOKEN, CLOUDFLARE_GLOBAL_API_KEY, CLOUDFLARE_USER_API_TOKEN,
    EC_PRIVATE_KEY, ENCRYPTED_PRIVATE_KEY, GITHUB_APP_INSTALLATION_TOKEN, GITHUB_APP_REFRESH_TOKEN,
    GITHUB_APP_USER_TOKEN, GITHUB_CLASSIC_PAT, GITHUB_FINE_GRAINED_PAT, GITHUB_OAUTH_TOKEN,
    GITHUB_STATELESS_INSTALLATION_TOKEN, GITLAB_ACCESS_TOKEN, GITLAB_AGENT_TOKEN,
    GITLAB_CI_JOB_TOKEN, GITLAB_DEPLOY_TOKEN, GITLAB_FEATURE_FLAG_CLIENT_TOKEN, GITLAB_FEED_TOKEN,
    GITLAB_INCOMING_MAIL_TOKEN, GITLAB_OAUTH_APPLICATION_SECRET,
    GITLAB_REGISTRATION_DERIVED_RUNNER_AUTH_TOKEN, GITLAB_RUNNER_AUTH_TOKEN, GITLAB_SCIM_TOKEN,
    GITLAB_TRIGGER_TOKEN, GITLAB_WORKSPACE_TOKEN, OPENSSH_PRIVATE_KEY, PGP_PRIVATE_KEY,
    PKCS8_PRIVATE_KEY, RSA_PRIVATE_KEY, SIGNED_JWT, SLACK_APP_LEVEL_TOKEN, SLACK_BOT_TOKEN,
    SLACK_USER_TOKEN, SLACK_WORKFLOW_TOKEN, STRIPE_LIVE_RESTRICTED_KEY, STRIPE_LIVE_SECRET_KEY,
    STRIPE_TEST_RESTRICTED_KEY, STRIPE_TEST_SECRET_KEY, STRIPE_WEBHOOK_SIGNING_SECRET,
    TELEGRAM_BOT_TOKEN,
};

use crate::RuleSpec;

/// Complete built-in rule pack currently supported by the scanner core.
pub const CURRENT: &[RuleSpec] = &[
    GITHUB_CLASSIC_PAT,
    GITHUB_FINE_GRAINED_PAT,
    GITHUB_OAUTH_TOKEN,
    GITHUB_APP_USER_TOKEN,
    GITHUB_APP_INSTALLATION_TOKEN,
    GITHUB_STATELESS_INSTALLATION_TOKEN,
    GITHUB_APP_REFRESH_TOKEN,
    GITLAB_ACCESS_TOKEN,
    GITLAB_OAUTH_APPLICATION_SECRET,
    GITLAB_DEPLOY_TOKEN,
    GITLAB_RUNNER_AUTH_TOKEN,
    GITLAB_REGISTRATION_DERIVED_RUNNER_AUTH_TOKEN,
    GITLAB_CI_JOB_TOKEN,
    GITLAB_TRIGGER_TOKEN,
    GITLAB_FEED_TOKEN,
    GITLAB_INCOMING_MAIL_TOKEN,
    GITLAB_AGENT_TOKEN,
    GITLAB_WORKSPACE_TOKEN,
    GITLAB_SCIM_TOKEN,
    GITLAB_FEATURE_FLAG_CLIENT_TOKEN,
    STRIPE_LIVE_SECRET_KEY,
    STRIPE_TEST_SECRET_KEY,
    STRIPE_LIVE_RESTRICTED_KEY,
    STRIPE_TEST_RESTRICTED_KEY,
    STRIPE_WEBHOOK_SIGNING_SECRET,
    CLOUDFLARE_GLOBAL_API_KEY,
    CLOUDFLARE_USER_API_TOKEN,
    CLOUDFLARE_ACCOUNT_API_TOKEN,
    SLACK_BOT_TOKEN,
    SLACK_USER_TOKEN,
    SLACK_APP_LEVEL_TOKEN,
    SLACK_WORKFLOW_TOKEN,
    TELEGRAM_BOT_TOKEN,
    SIGNED_JWT,
    PKCS8_PRIVATE_KEY,
    ENCRYPTED_PRIVATE_KEY,
    RSA_PRIVATE_KEY,
    EC_PRIVATE_KEY,
    OPENSSH_PRIVATE_KEY,
    PGP_PRIVATE_KEY,
    AWS_ACCESS_KEY_ID,
    AWS_TEMPORARY_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    AWS_SESSION_TOKEN,
    AZURE_CLIENT_SECRET,
    AZURE_STORAGE_ACCOUNT_KEY,
    AZURE_SHARED_ACCESS_SIGNATURE,
    GCP_PRIVATE_KEY_ID,
    GCP_PRIVATE_KEY,
    GCP_ESCAPED_PRIVATE_KEY,
    DOCKER_REGISTRY_AUTH,
    NPM_REGISTRY_AUTH_TOKEN,
    NPM_REGISTRY_AUTH,
    NPM_REGISTRY_PASSWORD,
    CARGO_REGISTRY_ENV_TOKEN,
    CARGO_REGISTRY_TOKEN,
    NETRC_PASSWORD,
    PASSWORD_FIELD,
    DATABASE_PASSWORD_FIELD,
    DATABASE_CONNECTION_PASSWORD,
    PASSPHRASE_FIELD,
    SENSITIVE_HASH,
    GENERIC_API_KEY,
    GENERIC_AUTH_TOKEN,
    AUTHORIZATION_BEARER,
    AUTHORIZATION_BASIC,
    GENERIC_SECRET,
    WIREGUARD_PRESHARED_KEY,
    WIREGUARD_PRIVATE_KEY,
    SHADOW_PASSWORD_VERIFIER,
    HTPASSWD_PASSWORD_VERIFIER,
];

use std::sync::{Arc, LazyLock};

use crate::{Scanner, compiled_rule::CompiledRuleSet};

static CURRENT_COMPILED: LazyLock<Arc<CompiledRuleSet>> = LazyLock::new(|| {
    let rules = CURRENT
        .iter()
        .map(|spec| spec.to_rule())
        .collect::<Result<Vec<_>, _>>()
        .expect("builtin rules must be valid");

    Arc::new(CompiledRuleSet::compile(rules).expect("builtin rules must compile"))
});

pub(crate) fn current_scanner() -> Scanner {
    Scanner::new(Arc::clone(&CURRENT_COMPILED))
}
